name: kronio_prueba
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true